title: Charly Román Blog 
email: charly@croman.mx
description: >
  My Blog personal, desarrollo, linux, tecnología general.
url: "http://yourdomain.com" 
twitter_username: Carlangueitor
github_username: Carlangueitor
markdown: kramdown
timezone: America/Mexico_City
permalink: /:categories/:title

